export const BUY_INGREDIENTS_SUCCESS = "BUY_INGREDIENTS_SUCCESS";
export const BUY_INGREDIENTS_FAILURE = "BUY_INGREDIENTS_FAILURE";
export const CREATE_BEER_SUCCESS = "CREATE_BEER_SUCCESS";
export const CREATE_BEER_FAILURE = "CREATE_BEER_FAILURE";
export const CREATE_BEER_REQUEST = "CREATE_BEER_REQUEST";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS";
export const CLOSE_BAR = "CLOSE_BAR";
export const CUSTOMERS_DRINKING = "CUSTOMERS_DRINKING";
